version: "3.3"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "admin"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "pass"
    ports:
      - "3306:3306"
    volumes:
      - ssmple_db:/var/lib/mysql

volumes:
  ssmple_db:
